name: Update RF10Y Gist

on:
  workflow_dispatch:
    inputs:
      currency:
        description: "sgd or usd"
        required: true
        default: "sgd"
      year:
        description: "YYYY (e.g. 2025)"
        required: true
        default: "2025"
      month:
        description: "Mon (Jan..Dec)"
        required: true
        default: "Aug"
      value:
        description: "Percent as number (e.g. 2.70)"
        required: true
        default: "2.70"
      gist_id:
        description: "Target Gist ID"
        required: true
        default: "fb7a8e9b365b5a05f47c6223b54c6676"
      filename:
        description: "Filename in gist"
        required: true
        default: "rf10y"
      raw_url:
        description: "Raw URL for reading current JSON"
        required: true
        default: "https://gist.githubusercontent.com/websbp/fb7a8e9b365b5a05f47c6223b54c6676/raw/rf10y"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run updater
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          python .github/scripts/update_gist.py \
            --gist-id "${{ inputs.gist_id }}" \
            --filename "${{ inputs.filename }}" \
            --raw-url "${{ inputs.raw_url }}" \
            --currency "${{ inputs.currency }}" \
            --year "${{ inputs.year }}" \
            --month "${{ inputs.month }}" \
            --value "${{ inputs.value }}"
